language: go
install: true
go:
  - 1.7.3
  - tip
env:
  global:
    - GOARCH=amd64
    - GO_FOR_RELEASE=1.7.1
script:
  - make test
notifications:
  email:
    on_success: change
    on_failure: always

